version: '2'

volumes:
  yb-master-n1-data-1:
  yb-master-n2-data-1:
  yb-master-n3-data-1:
  yb-tserver-n1-data-1:
  yb-tserver-n2-data-1:
  yb-tserver-n3-data-1:

services:
  yb-master-n1:
    image: yugabytedb/yugabyte:latest
    container_name: yb-master-n1
    volumes:
      - yb-master-n1-data-1:/mnt/master
    command: [ "/home/yugabyte/bin/yb-master",
               "--fs_data_dirs=/mnt/master",
               "--master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
               "--rpc_bind_addresses=yb-master-n1:7100",
               "--replication_factor=3"]
    environment:
      SERVICE_7000_NAME: yb-master
    ports:
      - "7000:7000"
      - "7100:7100"

  yb-master-n2:
    image: yugabytedb/yugabyte:latest
    container_name: yb-master-n2
    volumes:
      - yb-master-n2-data-1:/mnt/master
    command: [ "/home/yugabyte/bin/yb-master",
               "--fs_data_dirs=/mnt/master",
               "--master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
               "--rpc_bind_addresses=yb-master-n2:7100",
               "--replication_factor=3"]
    environment:
      SERVICE_7000_NAME: yb-master
  yb-master-n3:
    image: yugabytedb/yugabyte:latest
    container_name: yb-master-n3
    volumes:
      - yb-master-n3-data-1:/mnt/master
    command: [ "/home/yugabyte/bin/yb-master",
               "--fs_data_dirs=/mnt/master",
               "--master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
               "--rpc_bind_addresses=yb-master-n3:7100",
               "--replication_factor=3"]
    environment:
      SERVICE_7000_NAME: yb-master

  yb-tserver-n1:
    image: yugabytedb/yugabyte:latest
    container_name: yb-tserver-n1
    volumes:
      - yb-tserver-n1-data-1:/mnt/tserver
    command: [ "/home/yugabyte/bin/yb-tserver",
               "--fs_data_dirs=/mnt/tserver",
               "--enable_ysql",
               "--rpc_bind_addresses=yb-tserver-n1:9100",
               "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100"]
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_6379_NAME: yedis
      SERVICE_9000_NAME: yb-tserver
    ports:
      - "9000:9000"
      - "9100:9100"
      - "5433:5433"
      - "9042:9042"
      - "6379:6379"
    depends_on:
      - yb-master-n1
      - yb-master-n2
      - yb-master-n3
  yb-tserver-n2:
    image: yugabytedb/yugabyte:latest
    container_name: yb-tserver-n2
    volumes:
      - yb-tserver-n2-data-1:/mnt/tserver
    command: [ "/home/yugabyte/bin/yb-tserver",
               "--fs_data_dirs=/mnt/tserver",
               "--enable_ysql",
               "--rpc_bind_addresses=yb-tserver-n2:9100",
               "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100"]
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_6379_NAME: yedis
      SERVICE_9000_NAME: yb-tserver
    depends_on:
      - yb-master-n1
      - yb-master-n2
      - yb-master-n3
  yb-tserver-n3:
    image: yugabytedb/yugabyte:latest
    container_name: yb-tserver-n3
    volumes:
      - yb-tserver-n3-data-1:/mnt/tserver
    command: [ "/home/yugabyte/bin/yb-tserver",
               "--fs_data_dirs=/mnt/tserver",
               "--enable_ysql",
               "--rpc_bind_addresses=yb-tserver-n3:9100",
               "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100"]
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_6379_NAME: yedis
      SERVICE_9000_NAME: yb-tserver
    depends_on:
      - yb-master-n1
      - yb-master-n2
      - yb-master-n3

#  lb:
#    image: haproxy:lts
#    container_name: lb
#    volumes:
#      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
#    ports:
#      - "9000:9000"
##      - "9100:9100"
#      - "7000:7000"
##      - "7100:7100"
#      - "5433:5433"
#      - "9042:9042"
##      - "6379:6379"
#
#    depends_on:
#      - yb-master-n1
#      - yb-master-n2
#      - yb-master-n3
#      - yb-tserver-n1
#      - yb-tserver-n2
#      - yb-tserver-n3

